### ISSUE TITLE
The error occurred during compileInlining.

### ISSUE THREAD

**Issue by CyanTachyon** [SMILEY4/schema-kenerator#39] opened 2024-10-25 13:01 UTC
```
java.lang.NullPointerException: getTypes(...) must not be null
   at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileInlineStep.compile$lambda$1(SwaggerSchemaCompileInlineStep.kt:30)
   at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileUtils.resolveReferences(SwaggerSchemaCompileUtils.kt:29)
   at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileUtils.resolveReferences(SwaggerSchemaCompileUtils.kt:37)
   at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileUtils.resolveReferences(SwaggerSchemaCompileUtils.kt:33)
   at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileUtils.resolveReferences(SwaggerSchemaCompileUtils.kt:36)
   at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileUtils.resolveReferences(SwaggerSchemaCompileUtils.kt:33)
   at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileUtils.resolveReferences(SwaggerSchemaCompileUtils.kt:37)
   at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileUtils.resolveReferences(SwaggerSchemaCompileUtils.kt:33)
   at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileUtils.resolveReferences(SwaggerSchemaCompileUtils.kt:37)
   at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileUtils.resolveReferences$default(SwaggerSchemaCompileUtils.kt:24)
   at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileInlineStep.compile(SwaggerSchemaCompileInlineStep.kt:23)
```

```kotlin
...
install(SwaggerUI) {
    ...
    schemas {
        generator = {
            it.processReflection()
                .generateSwaggerSchema()
                .withTitle(TitleType.SIMPLE)
                .compileInlining() // error here
        }
    }
    ...
}
```

This works fine in 1.4.3, but the above error occurs in 1.5.0.
However, if I replace `compileInlining` with `compileReferencingRoot`, no error occurs, so I think this is an issue with `compileInlining`?

**Comment by SMILEY4** [comment] 2024-11-11 20:51
Hi, 
that defenitly looks like an issue with compileInlining in schema-kenerator. Could you perhaps provide some model which i can use to reproduce the error?

**Comment by CyanTachyon** [comment] 2024-11-12 04:04
> Hi, that defenitly looks like an issue with compileInlining in schema-kenerator. Could you perhaps provide some model which i can use to reproduce the error?

This is the code I found to reproduce the issue minimally:
```kotlin
// any sealed class
sealed class SealedClass
// any class that extends the sealed class
class A: SealedClass()
// any class that has a nullable field of the sealed class
// must be a nullable field
class B(val a: SealedClass?)

fun main()
{
    val type = typeOf<B>()
    type
        .processReflection()
        .generateSwaggerSchema()
        .withTitle(TitleType.SIMPLE)
        .compileInlining() // error here
}
```

**Comment by SMILEY4** [comment] 2024-11-17 12:43
Ah, thank you.
i fount the issue. The bug should be fixed in the next version :+1:

**Closed as completed by SMILEY4** 2024-11-17 12:43 UTC
